development:
  dialect: sqlite3
  database: chatter_development

test:
  dialect: postgres
  database: chatter_test
  user: postgres
  password: postgres
  host: 127.0.0.1

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/chatter_production"}}
